CREATE TABLE IF NOT EXISTS authors
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    version   BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_authors_full_name UNIQUE (full_name)
);

CREATE TABLE IF NOT EXISTS genres
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    version BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_genres_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email ON users (email);

CREATE TABLE IF NOT EXISTS user_roles
(
    user_id BIGINT      NOT NULL,
    role    VARCHAR(32) NOT NULL,
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_roles_user_role UNIQUE (user_id, role)
);

CREATE TABLE IF NOT EXISTS books
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR(255) NOT NULL,
    author_id BIGINT       NOT NULL,
    version   BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uq_books_author_title UNIQUE (author_id, title),
    CONSTRAINT fk_books_author_no_cascade
        FOREIGN KEY (author_id) REFERENCES authors (id) ON DELETE NO ACTION
);
CREATE INDEX IF NOT EXISTS idx_books_author_id ON books (author_id);

CREATE TABLE IF NOT EXISTS books_genres
(
    book_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, genre_id),

    CONSTRAINT fk_bg_book_cascade
        FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
    CONSTRAINT fk_bg_genre_no_cascade
        FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE NO ACTION
);
CREATE INDEX IF NOT EXISTS idx_books_genres_genre_id ON books_genres (genre_id);

CREATE TABLE IF NOT EXISTS comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR(2048)            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    book_id    BIGINT                   NOT NULL,
    user_id    BIGINT                   NOT NULL,
    version    BIGINT                   NOT NULL DEFAULT 0,

    CONSTRAINT fk_comments_book_cascade
        FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,

    CONSTRAINT fk_comments_user_restrict
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_comments_book_created_at ON comments (book_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments (user_id);
