ALTER TABLE comments ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE comments ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE comments ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
