services:
  mongo:
    image: mongo:7.0
    container_name: mongo-local
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: library
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
