
-- AUTHORS
CREATE TABLE authors
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    version   BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_authors_full_name UNIQUE (full_name)
);

-- GENRES
CREATE TABLE genres
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    version BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_genres_name UNIQUE (name)
);

-- BOOKS
CREATE TABLE books
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR(255) NOT NULL,
    author_id BIGINT       NOT NULL,
    version   BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_books_author_title UNIQUE (author_id, title),
    CONSTRAINT fk_books_author_no_cascade
        FOREIGN KEY (author_id)
            REFERENCES authors (id)
            ON DELETE NO ACTION
);
CREATE INDEX idx_books_author_id ON books (author_id);

-- BOOKS_GENRES (link table)
CREATE TABLE books_genres
(
    book_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, genre_id),
    CONSTRAINT fk_bg_book_cascade
        FOREIGN KEY (book_id)
            REFERENCES books (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_bg_genre_no_cascade
        FOREIGN KEY (genre_id)
            REFERENCES genres (id)
            ON DELETE NO ACTION
);
CREATE INDEX idx_books_genres_genre_id ON books_genres (genre_id);

-- COMMENTS
CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR(2048)            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    book_id    BIGINT                   NOT NULL,
    version    BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT fk_comments_book_cascade
        FOREIGN KEY (book_id)
            REFERENCES books (id)
            ON DELETE CASCADE
);
CREATE INDEX idx_comments_book_created_at ON comments (book_id, created_at DESC);
