spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: app
      hibernate.jdbc.fetch_size: 1000
      hibernate.jdbc.batch_size: 50

  data:
    mongodb:
      uri: mongodb://localhost:27017/library

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  flyway:
    enabled: true
    create-schemas: true
    default-schema: app
    schemas: app

logging.level.org.springframework.batch: INFO

